### PR TITLE
API Change: Export function instead of component.

### PR DESCRIPTION
**Pull request by brentropy**
- No need to handle willReceiveProps
- Easier to use

### CODE REVIEW

**Comment by aaronshaf** [comment]
:+1:

**Comment by vanwagonet** [comment]
I like this a lot. :100: 
- You aren't setting props on a wrapper, and then something (store.state) else gets passed to a child. -reduces confusion.
- The implementation is simpler because you don't need to monitor `componentWillRecieveProps`.

**Comment by brentropy** [comment]
Sounds like there is no opposition to the change.

**Comment by brentropy** [comment]
`uniflow-component@2.0.0` published to npm

**Pull request merged**
