### PR TITLE
copy statics from source Component to UniflowComponent

### PR DESCRIPTION
**Pull request by vanwagonet**

### CODE REVIEW

**Comment by aaronshaf** [comment]
:+1:

**Comment by aaronshaf** [comment]
@brentburg ?

**Comment by brentropy** [comment]
It seems like we had talked about this before and came to the conclusion that it was easy enough to do on your own if you want this that it would be better not to force this.

``` js
Object.assign(uniflowComponent(Foo, {bar: BarStore}), Foo)
```

I could be persuaded otherwise though. What cases are there where this is beneficial? Could there be any times where this would cause unexpected behavior?

One potentially bad one that I am thinking of is `propTypes`. If you define the store state props as required props in the component it could cause problems since the wrapped component will not be expecting those props.

Thoughts?

**Comment by vanwagonet** [comment]
You're right. While many properties are probably good to copy, propTypes definitely shouldn't be copied, and displayName probably shouldn't either. I could explicitly remove those, or we can abandon this idea.

**Pull request closed without merging**
